apiVersion: pais.vmware.com/v1alpha1
kind: ModelEndpoint
metadata:
  annotations:
    pais.vmware.com/displayName: qwen3.8-27b
    ui.pais.vmware.com/model-info-secret: pais-pais-reg-creds-ebccdf1b-7923-4f40-b7c7-2fafa33f0437
  generateName: qwen3.8-27b
spec:
  engine: LlamaCPP
  inferenceServerCustomization:
    cliArgs:
      - '--n-gpu-layers'
      - '99'
      - '--ctx-size'
      - '60000'
      - '--cache-type-k'
      - 'q8_0'
      - '--cache-type-v'
      - 'q8_0'
      - '--jinja'
      - '--batch-size'
      - '2048'
      - '--ubatch-size'
      - '512'
      - '--parallel'
      - '1'
      - '--flash-attn'
      - 'on'
      - '--cache-prompt'
      - '--metrics'
      - '-lv'
      - '4'
    engineImage: ghcr.io/ggml-org/llama.cpp:server-cuda
  model:
    ociRef: vis.vcf.lab:9443/models/unsloth/qwen3.8-27b-gguf:v1.0
    pullSecrets:
      - name: pais-pais-reg-creds-ebccdf1b-7923-4f40-b7c7-2fafa33f0437
  replicas: 1
  routingName: qwen3.8-27b
  storageClassName: vcf-mgmt-cluster-optimal-datastore-default-policy-autoraid
  type: Completions
  virtualMachineClassName: nvidia-a4000-rtx